//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Master.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class externaluser_regifrom
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string company_name { get; set; }
        public string email_id { get; set; }
        public Nullable<int> contact_no { get; set; }
        public string contact_person { get; set; }
        public string gst_no { get; set; }
        public string pan_no { get; set; }
        public string tan_no { get; set; }
        public string dd_balancesheet { get; set; }
        public string kyc_msdeoraadharudyam { get; set; }
        public string kyc_iec { get; set; }
        public string indurstry { get; set; }
        public string indurstry_category { get; set; }
        public string indurstry_subcategory { get; set; }
        public string bi_headoffice_address { get; set; }
        public string bi_headoffice_country { get; set; }
        public string bi_headoffice_state { get; set; }
        public string bi_headoffice_city { get; set; }
        public Nullable<int> bi_headoffice_fax { get; set; }
        public string bi_headoffice_companywebsite { get; set; }
        public Nullable<System.DateTime> type_of_establishment { get; set; }
        public string type_of_companyregistration { get; set; }
        public string nature_of_business { get; set; }
        public string certification { get; set; }
    }
}
