//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Master.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class internaluser
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string designation { get; set; }
        public string employee_id { get; set; }
        public string email_id { get; set; }
        
    }
}
