//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Master.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public string Grade { get; set; }
        public string Unit_Of_Measurement { get; set; }
        public Nullable<int> HS_Code { get; set; }
        public string Manufacturer { get; set; }
        public string Country { get; set; }
        public string TDS { get; set; }
        public string MSDS { get; set; }
        public string Free_Trade_Agreement { get; set; }
        public byte[] Image { get; set; }
    }
}
